---
- name: Deploy Unit Converter Application
  hosts: webserver
  become: yes

  vars:
    docker_image: "yourdockerhub/unit-converter:latest"
    container_name: "unit-converter-app"
    app_port: 8080

  tasks:

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Stop existing container (if running)
      docker_container:
        name: "{{ container_name }}"
        state: stopped
        ignore_errors: yes

    - name: Remove existing container
      docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: yes
        ignore_errors: yes

    - name: Run new container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ app_port }}:8080"
